use {
    crate::{
        error::AdrenaError,
        state::{cortex::Cortex, user_profile::UserProfile},
        utils::limited_string::LimitedString,
    },
    anchor_lang::prelude::*,
    anchor_spl::token::{Mint, Token, TokenAccount},
};

#[derive(Accounts)]
#[instruction(nickname: String)]
pub struct EditUserProfileNickname<'info> {
    /// #1
    #[account(mut)]
    pub owner: Signer<'info>,

    /// #2
    #[account(
        mut,
        seeds = [b"cortex"],
        bump = cortex.load()?.bump,
        constraint = cortex.load()?.is_initialized() @AdrenaError::InvalidCortexState
    )]
    pub cortex: AccountLoader<'info, Cortex>,

    /// #3
    #[account(
        mut,
        seeds = [b"user_profile",
            owner.key().as_ref()],
        bump = user_profile.load()?.bump
    )]
    pub user_profile: AccountLoader<'info, UserProfile>,

    /// #4
    #[account(
        mut,
        constraint = funding_account.mint == lm_token_mint.key(),
        constraint = funding_account.owner == owner.key() @AdrenaError::InvalidAccountData,
    )]
    pub funding_account: Box<Account<'info, TokenAccount>>,

    /// #5
    #[account(
        mut,
        seeds = [b"lm_token_mint"],
        bump = cortex.load()?.lm_token_bump
    )]
    pub lm_token_mint: Box<Account<'info, Mint>>,

    /// #6
    /// CHECK: Empty account
    #[account(mut)]
    pub old_user_nickname: Option<UncheckedAccount<'info>>,

    /// #7
    /// Use PDA to make nicknames unique
    /// CHECK: Empty account
    #[account(
        init,
        payer = owner,
        space = 0,
        seeds = [b"nickname", nickname.as_bytes()],
        bump
    )]
    pub user_nickname: AccountInfo<'info>,

    /// #8
    pub system_program: Program<'info, System>,

    /// #9
    pub token_program: Program<'info, Token>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct EditUserProfileNicknameParams {
    pub nickname: String,
}

pub fn edit_user_profile_nickname(
    ctx: Context<EditUserProfileNickname>,
    params: &EditUserProfileNicknameParams,
) -> Result<()> {
    // Preliminary checks
    {
        require!(
            params.nickname.len() <= 24,
            AdrenaError::UserNicknameTooLong
        );

        require!(
            params.nickname.len() >= 3,
            AdrenaError::UserNicknameTooShort
        );
    }

    let mut user_profile = ctx.accounts.user_profile.load_mut()?;

    // Check if the user currently has a nickname
    if user_profile.nickname.length > 0 {
        // Pay tax to change the nickname except if the nickname was auto-generated
        if !UserProfile::is_autogenerated_default_nickname(&params.nickname) {
            let cortex = ctx.accounts.cortex.load_mut()?;

            cortex.burn_tokens_from_user(
                ctx.accounts.lm_token_mint.to_account_info(),
                ctx.accounts.funding_account.to_account_info(),
                ctx.accounts.owner.to_account_info(),
                ctx.accounts.token_program.to_account_info(),
                UserProfile::CHANGE_NICKNAME_TAX,
            )?;
        }

        // Derive the old nickname PDA dynamically
        let (old_nickname_pda, _old_bump) = Pubkey::find_program_address(
            &[b"nickname", user_profile.nickname.to_bytes()],
            ctx.program_id,
        );

        if let Some(old_nickname_account) = ctx.accounts.old_user_nickname.as_ref() {
            require!(
                old_nickname_account.key() == old_nickname_pda,
                AdrenaError::InvalidAccountData
            );

            // Transfer SOL from the old nickname PDA to the owner before closing
            Cortex::transfer_sol_from_owned(
                old_nickname_account.to_account_info(),
                ctx.accounts.owner.to_account_info(),
                old_nickname_account.lamports(),
            )?;
        } else {
            // The old nickname PDA should exist
            return Err(AdrenaError::InvalidAccountData.into());
        }
    }

    user_profile.nickname = LimitedString::new(params.nickname.clone());

    Ok(())
}
