use {
    crate::{
        error::AdrenaError,
        state::{
            cortex::Cortex,
            user_profile::{Continent, ProfilePicture, Team, Title, UserProfile, Wallpaper},
        },
        utils::limited_string::LimitedString,
    },
    anchor_lang::prelude::*,
};

#[derive(Accounts)]
#[instruction(nickname: String)]
pub struct InitUserProfile<'info> {
    /// #1
    /// CHECK: Can be owner or another user account, if owner is not the caller, it is permissionless
    pub user: AccountInfo<'info>,

    /// #2
    pub caller: Signer<'info>,

    /// #3
    #[account(mut)]
    pub payer: Signer<'info>,

    /// #4
    #[account(
        init,
        payer = payer,
        space = UserProfile::LEN,
        seeds = [b"user_profile",
                 user.key().as_ref()],
        bump
    )]
    pub user_profile: AccountLoader<'info, UserProfile>,

    /// #5
    /// Use PDA to make nicknames unique
    /// CHECK: Empty account
    #[account(
        init,
        payer = payer,
        space = 0,
        seeds = [b"nickname", nickname.as_bytes()],
        bump
    )]
    pub user_nickname: AccountInfo<'info>,

    /// #6
    /// Apply this referrer to the user profile, If none, referrer_profile is set to default
    pub referrer_profile: Option<AccountLoader<'info, UserProfile>>,

    /// #7
    #[account(
        mut,
        seeds = [b"cortex"],
        bump = cortex.load()?.bump,
        constraint = cortex.load()?.is_initialized() @AdrenaError::InvalidCortexState
    )]
    pub cortex: AccountLoader<'info, Cortex>,

    /// #8
    pub system_program: Program<'info, System>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct InitUserProfileParams {
    pub nickname: String,
    pub profile_picture: u8,
    pub wallpaper: u8,
    pub title: u8,
    pub team: u8,
    pub continent: u8,
}

// IX becomes permissionless to allow users to create profiles for other users
// It is needed for S2 because officers need to have a user profile in order to assign a team
pub fn init_user_profile(
    ctx: Context<InitUserProfile>,
    params: &InitUserProfileParams,
) -> Result<()> {
    // Preliminary checks
    {
        require!(
            params.nickname.len() <= 24,
            AdrenaError::UserNicknameTooLong
        );

        require!(
            params.nickname.len() >= 3,
            AdrenaError::UserNicknameTooShort
        );

        if ctx.accounts.caller.key() != ctx.accounts.user.key() {
            if !UserProfile::is_autogenerated_default_nickname(&params.nickname) {
                return Err(AdrenaError::UserNicknameInvalidFormat.into());
            }

            // When caller is not the user, cannot set a referrer profile
            require!(
                ctx.accounts.referrer_profile.is_none(),
                AdrenaError::InvalidAccountData
            );
        }

        require!(
            Wallpaper::try_from(params.wallpaper).is_ok(),
            AdrenaError::InvalidWallpaperOrProfilePictureOrTitle,
        );

        require!(
            ProfilePicture::try_from(params.profile_picture).is_ok(),
            AdrenaError::InvalidWallpaperOrProfilePictureOrTitle,
        );

        require!(
            ProfilePicture::try_from(params.title).is_ok(),
            AdrenaError::InvalidWallpaperOrProfilePictureOrTitle,
        );

        // Cannot set yourself as a referrer
        if let Some(referrer_profile) = ctx.accounts.referrer_profile.as_ref() {
            require!(
                referrer_profile.key().ne(&ctx.accounts.user_profile.key()),
                AdrenaError::InvalidAccountData,
            );
        }
    }

    {
        let mut user_profile = ctx.accounts.user_profile.load_init()?;

        user_profile.bump = ctx.bumps.user_profile;

        user_profile.nickname = LimitedString::new(params.nickname.clone());

        user_profile.created_at = ctx.accounts.cortex.load()?.get_time()?;

        user_profile.owner = ctx.accounts.user.key();

        user_profile.version = UserProfile::VERSION;

        // For permissionless profile creation, always use defaults
        if ctx.accounts.caller.key() != ctx.accounts.user.key() {
            user_profile.profile_picture = ProfilePicture::Zero as u8;
            user_profile.wallpaper = Wallpaper::Zero as u8;
            user_profile.title = Title::Zero as u8;
            user_profile.team = Team::Default as u8;
            user_profile.continent = Continent::Default as u8;
            user_profile.referrer_profile = Pubkey::default();
        } else {
            user_profile.profile_picture = params.profile_picture;
            user_profile.wallpaper = params.wallpaper;
            user_profile.title = params.title;
            user_profile.team = params.team;
            user_profile.continent = params.continent;

            if let Some(referrer_profile) = ctx.accounts.referrer_profile.as_ref() {
                user_profile.referrer_profile = referrer_profile.key();
            } else {
                user_profile.referrer_profile = Pubkey::default();
            }
        }
    }

    ctx.accounts.cortex.load_mut()?.user_profiles_count += 1;

    Ok(())
}
