use {
    crate::{
        error::AdrenaError,
        state::{
            cortex::Cortex,
            user_profile::{
                legacy::UserProfileV1, Continent, ProfilePicture, Team, Title, UserProfile,
                UserProfileVersion, Wallpaper,
            },
        },
        utils::limited_string::LimitedString,
    },
    anchor_lang::prelude::*,
    anchor_spl::token::Token,
};

#[derive(Accounts)]
#[instruction(nickname: String)]
pub struct MigrateUserProfileFromV1ToV2<'info> {
    /// #1
    /// Wallet related to the user profile
    /// CHECK: This is the owner of the user profile
    pub owner: AccountInfo<'info>,

    /// #2
    pub caller: Signer<'info>,

    /// #3
    #[account(mut)]
    pub payer: Signer<'info>,

    /// #4
    /// CHECK: Manual deserialization is used
    #[account(
        mut,
        seeds = [b"user_profile",
            owner.key().as_ref()],
        bump,
    )]
    pub user_profile: AccountInfo<'info>,

    /// #5
    /// Use PDA to make nicknames unique
    /// CHECK: Empty account
    #[account(
        init,
        payer = payer,
        space = 0,
        seeds = [b"nickname", nickname.as_bytes()],
        bump
    )]
    pub user_nickname: AccountInfo<'info>,

    /// #6
    pub system_program: Program<'info, System>,

    /// #7
    pub token_program: Program<'info, Token>,

    /// #8
    pub rent: Sysvar<'info, Rent>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct MigrateUserProfileFromV1ToV2Params {
    pub nickname: String,
}

pub fn migrate_user_profile_from_v1_to_v2<'info>(
    ctx: Context<'_, '_, '_, 'info, MigrateUserProfileFromV1ToV2<'info>>,
    params: &MigrateUserProfileFromV1ToV2Params,
) -> Result<()> {
    let user_profile_account_info = &ctx.accounts.user_profile;

    // Preliminary checks
    {
        require!(
            params.nickname.len() <= 24,
            AdrenaError::UserNicknameTooLong
        );

        require!(
            params.nickname.len() >= 3,
            AdrenaError::UserNicknameTooShort
        );
    }

    // Manually deserialize the old UserProfileV1
    let user_profile_v1_data: UserProfileV1 = {
        let data = user_profile_account_info.try_borrow_data()?;
        let slice = &data[8..]; // Skip discriminator

        *bytemuck::try_from_bytes(slice)
            .map_err(|_| anchor_lang::error::ErrorCode::AccountDidNotDeserialize)?
    };

    // Ensure the old version is correct
    require!(
        user_profile_v1_data.version == UserProfileVersion::V1 as u8,
        AdrenaError::InvalidVersion,
    );

    // If called permissionlessly, nickname must be either the same as it was, or match a specific pattern
    if ctx.accounts.caller.key() != ctx.accounts.owner.key() {
        require!(
            user_profile_v1_data.nickname.to_string() == params.nickname
                || UserProfile::is_autogenerated_default_nickname(&params.nickname),
            AdrenaError::UserNicknameInvalidFormat,
        );
    }

    Cortex::realloc(
        ctx.accounts.payer.to_account_info(),
        user_profile_account_info.clone(),
        ctx.accounts.system_program.to_account_info(),
        UserProfile::LEN,
        false, // Already initialized by 0
    )?;

    // Initialize the new User profile structure
    {
        let mut data = user_profile_account_info.try_borrow_mut_data()?;
        let new_user_profile: &mut UserProfile = bytemuck::from_bytes_mut(&mut data[8..]); // Skip discriminator

        // Update to the new version
        new_user_profile.version = UserProfileVersion::V2 as u8;

        // Set the new nickname
        new_user_profile.nickname = LimitedString::new(params.nickname.clone());

        // Initialize new fields in UserProfile
        new_user_profile.profile_picture = ProfilePicture::Zero as u8;
        new_user_profile.wallpaper = Wallpaper::Zero as u8;
        new_user_profile.title = Title::Zero as u8;
        new_user_profile.team = Team::Default as u8;
        new_user_profile.continent = Continent::Default as u8;
        new_user_profile.achievements = [0; 256]; // Empty achievements array (Note: it erase the old data stored at same byte location in V1)
        new_user_profile.referrer_profile = Pubkey::default();
        new_user_profile.claimable_referral_fee_usd = 0;
        new_user_profile.total_referral_fee_usd = 0;
        new_user_profile._padding2 = [0; 16]; // Ensure padding is zeroed
    }

    Ok(())
}
